### ISSUE TITLE
3.1.c) As a DEVELOPER, we want to AUTOMATICALLY FORMAT CODE whenever it is edited so that CONSISTENCY AND READABILITY ARE MAINTAINED across the codebase

### ISSUE THREAD

**Issue by JaSNOHo** [ITU-BDSA2024-GROUP30/Chirp#10]
Acceptance Criteria:
- Ensure that VSCode IDE automatically formats code on save or edit.
- Document and share the configuration with the team to ensure consistency.
- Validate that all new code submissions follow the enforced formatting standards.

**Comment by Thyme-Cat** [comment]
From slides session 4 slide 6, he writes "add an .editorconfig file, so that you apply all the same code conventions."
