### ISSUE TITLE
as a USER I want to READ THE README such that I UNDERSTAND WHAT THE CHIRP 30 PROGRAM DOES

### ISSUE THREAD

**Issue by Thyme-Cat** [ITU-BDSA2024-GROUP30/Chirp#103]
Acceptance criteria:
- description of chirps purpose (it is a knock-off twitter)
- description of how to run the program locally depending on your device and on the web.
- including the license

**Comment by tomat-suppe** [comment]
Done, license not needed as it is next to read me, and how to run program is written in the report
