### ISSUE TITLE
As a DEVELOPER I want to USE AN EXTERNAL CSVFILE HANDLER so that AMOUNT OF CODE IS REDUCED+READABILITY IS IMPROVED

### ISSUE THREAD

**Issue by tomat-suppe** [ITU-BDSA2024-GROUP30/Chirp#2]
Acceptance criteria:
* Add CsvHelper library to project
* Configure CsvHelper
  - Needs to recognize _our_ cheep input
* Refactor code to instantiate Cheeps using our implemented CsvHelper library

**Comment by HenrijetteOest** [comment]
b

**Comment by HenrijetteOest** [comment]
a

**Comment by HenrijetteOest** [comment]
eventuelt lave en autoComplete på gæster som Guest as Author when we don't know or have a given author
