### ISSUE TITLE
(5.1.b.3) As DEVELOPERS we want TO DEFINE DEFAULT PAGINATION BEHAVIOR WHEN NO PAGE IS SPECIFIED

### ISSUE THREAD

**Issue by JaSNOHo** [ITU-BDSA2024-GROUP30/Chirp#36]
Acceptance Criteria:
- Ensure that when no page parameter is provided in the URL, the first page is returned by default.
   - For example, a request to http://<your_host>/ or http://<your_host>/Helge should return the first page of cheeps.
- Ensure this behavior is consistent across public and private timelines.
- Make sure to test the default behavior for both public and private timelines.

**Comment by tomat-suppe** [comment]
Technically fixed, should be closed when Pagination is merged to main
