### ISSUE TITLE
(d) As a DEVELOPER I want to USE AN EXTERNAL CLI PARSING LIBRARY so that ARGUMENT HANDLING IS MORE RELIABLE AND READABLE #X

### ISSUE THREAD

**Issue by JaSNOHo** [ITU-BDSA2024-GROUP30/Chirp#4]
Acceptance Criteria:
- Integrate a CLI parsing library (e.g., System.CommandLine, CommandLine, docopt.net).
- Refactor Program.cs to use the library instead of manual args parsing.
- Maintain existing argument handling functionality.

**Comment by HenrijetteOest** [comment]
d
