### ISSUE TITLE
(c) As a DEVELOPER I want to MOVE ALL CODE FOR PRINTING CHEEPS TO A NEW CLASS UserInterface so that all USER INTERFACE CODES RECIDES IN THE SAME PLACE

### ISSUE THREAD

**Issue by Thyme-Cat** [ITU-BDSA2024-GROUP30/Chirp#5]
Acceptance criteria:

- Make a new class called UserInterface 
- Move code regarding printing cheeps to the terminal from Chirp.CLI's Program.cs file to the new UserInterface class.
- Make the class and its contained methods "static"
- Have the main program call this UserInterface class when it wants to print cheeps to the terminal

**Comment by Thyme-Cat** [comment]
Assignment c) 
old code:
![Image](https://github.com/user-attachments/assets/9fcba370-7388-4c0d-9059-769e1ecfa43b)

After the issue:
![Image](https://github.com/user-attachments/assets/47ac8e1b-f99a-4049-a47e-9d76e7f647ac)

**Comment by HenrijetteOest** [comment]
c
