### ISSUE TITLE
(7.1.c) as DEVELOPERS we want to CONSTRAIN LENGTH OF CHEEPS OF 160 CH. because OUR CHIRP! APPLICATION SHOULD NOT ACCEPT CHEEPS LONGER THAN 160 CHARACTERS.

### ISSUE THREAD

**Issue by HenrijetteOest** [ITU-BDSA2024-GROUP30/Chirp#63]
Using the mechanisms presented by Adrian, ensure that only cheeps up to 160 characters length can be stored.

Constrain cheeps so that only cheeps of length 160 characters are considered valid. Your Chirp! application should not accept cheeps that are longer than 160 character. Such cheeps should never be stored to the database.

**Comment by tomat-suppe** [comment]
Fixed by Henriette
