### ISSUE TITLE
(7.1.d) as DEVELOPERS we want to ADD UNIT TESTS such that TESTS TO THE CURRENT CODE LAYOUT

### ISSUE THREAD

**Issue by HenrijetteOest** [ITU-BDSA2024-GROUP30/Chirp#64]
Now, that you have decoupled your data persistence code properly from your application, augment your test suite from last time.

Implement a set of unit tests for suitable functionality, e.g., all of the repository methods from the task above, data conversion, etc.

**Comment by tomat-suppe** [comment]
Make at least one test before 15/11 that RUNS on the CURRENT CODE!
