### ISSUE TITLE
(7.1.e) as DEVELOPERS we want to ENSURE METHODS THAT ARE EXPOSED IN OUR REPOSITORY ARE SEPERATED INTO COMMANDS AND QUERIES such that we HAVE LESS SIDE EFFECTS.

### ISSUE THREAD

**Issue by HenrijetteOest** [ITU-BDSA2024-GROUP30/Chirp#65]
https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_07/README_PROJECT.md#1e-command-query-separation
 
 "Separate Commands from Queries. Commands are procedures that have side effects. Queries are functions that return data. Every method should be either a Command or a Query, but not both. Source: Mark Seemann "Code That Fits in Your Head"

**Comment by tomat-suppe** [comment]
Done
