### ISSUE TITLE
(7.1g) as DEVELOPERS we want to ENSURE that our PROJECT BUILDS WITHOUT ANY WARNINGS and at least ADDRESS THE PRESENT WARNINGS

### ISSUE THREAD

**Issue by HenrijetteOest** [ITU-BDSA2024-GROUP30/Chirp#67]
Ensure that your project builds without any warnings. 
That is, make sure that all warnings in your code are addressed.

**Comment by tomat-suppe** [comment]
EF Core warning (x2): Problem with duplicate fields AuthorId in both Cheep and Author class. Laura will look at how to recognize foreign keys
Regular warning (x5): All problems with non-nullable fields.

Sophie will be helping on this.

Deadline 13/11
