### ISSUE TITLE
(6.1.1.1) as DEVELOPERS we want TO REFACTOR CHIRP.RAZOR to use EF CORE INSTEAD of DIRECT SQLite ACCESS

### ISSUE THREAD

**Issue by JaSNOHo** [ITU-BDSA2024-GROUP30/Chirp#70]
Acceptance Criteria:
- Application must use EF Core for all database interactions.
- Existing functionality (displaying public and private timelines, paginated to 32 cheeps per page) must remain unchanged.
- SQLite should remain the underlying database, but accessed through EF Core.

**Comment by tomat-suppe** [comment]
EF Core is implemented on Branch = ImplementingEFCore. However, EF Core syntax for queries is not yet completely correct, and therefore project does not build - yet.

**Comment by tomat-suppe** [comment]
If we want to reverse the migration, this is the terminal command: ef migrations remove

**Comment by tomat-suppe** [comment]
Sophie has taken ownership of this issue.
Deadline: 5/11

**Comment by tomat-suppe** [comment]
Pagination not implemented, but since the EFCore side of things runs, and pagination has its own issue, this will be closed
