### ISSUE TITLE
(6.1.1a) as DEVELOPERS we want to CREATE DATA MODEL for CHIRP.RAZOR

### ISSUE THREAD

**Issue by JaSNOHo** [ITU-BDSA2024-GROUP30/Chirp#71]
Acceptance Criteria:
- Implement Cheep class with properties: Text (string) and TimeStamp (DateTime).
- Implement Author class with properties: Name and Email (both strings).
- Each Cheep must reference an Author, and each Author must maintain a list of their Cheeps.
- No auto-conversion from last week's SQL schema; implement by hand.

**Comment by Thyme-Cat** [comment]
The one who did this is welcome to add their name to it.
