### ISSUE TITLE
(6.1.1d) as DEVELOPERS we want to SEED DATABASE with EXAMPLE DATA

### ISSUE THREAD

**Issue by JaSNOHo** [ITU-BDSA2024-GROUP30/Chirp#74]
Acceptance Criteria:
- Ensure DbInitializer.cs seeds example data into the database on application startup.
- Seeded data must include at least the authors and cheeps from DbInitializer.cs.
- The ChirpDBContext should call the DbInitializer method immediately after creation to populate the database.

**Comment by tomat-suppe** [comment]
Sophie has taken ownership of this issue - but Cat has also worked on it.
Deadline: 5/11
