### ISSUE TITLE
(8.1.a.1) As DEVELOPERS we want to IMPLEMENT ASP.NET CORE IDENTITY such that WE CAN ADD ACCOUNTS TO CHIRP

### ISSUE THREAD

**Issue by llsa-itu** [ITU-BDSA2024-GROUP30/Chirp#89]
Acceptance Criteria:

- The EF core data model has been updated to support Identity. 
- Chirp Database stores the users account information. 
- Users passwords are not stored as clear text in the database (by using Hashing) 
- Accounts for Helge and Adrian has been added to the database.

**Comment by Thyme-Cat** [comment]
- add navigation bar
- add "register" and "login" to navigation bar
- create "register" and "login" end points
